---
- hosts: all
  become: yes
  tasks:
  - name: apt-get update
    apt:
      update_cache: yes
  - name: apt-get upgrade
    apt:
      name: "*"
      state: latest
  - name: Remove useless packages from the cache
    apt:
      autoclean: yes
  - name: Remove useless packages from the system
    apt:
      autoremove: yes